const ENV_KEY = /^[A-Z_][A-Z0-9_]*$/;

function joinContinuations(raw = '') {
  const logical = [];
  let current = '';
  String(raw)
    .replace(/\r\n/g, '\n')
    .split('\n')
    .forEach((line) => {
      if (line.endsWith('\\')) {
        current += `${line.slice(0, -1)}\n`;
        return;
      }
      logical.push(current + line);
      current = '';
    });
  if (current) logical.push(current);
  return logical;
}

function stripInlineComment(value = '') {
  let quote = '';
  for (let index = 0; index < value.length; index += 1) {
    const char = value[index];
    const previous = value[index - 1];
    if ((char === '"' || char === "'") && previous !== '\\') {
      quote = quote === char ? '' : quote || char;
    }
    if (char === '#' && !quote && /\s/.test(previous || '')) {
      return value.slice(0, index).trimEnd();
    }
  }
  return value.trim();
}

function unquote(value = '') {
  const trimmed = stripInlineComment(value);
  if (
    (trimmed.startsWith('"') && trimmed.endsWith('"')) ||
    (trimmed.startsWith("'") && trimmed.endsWith("'"))
  ) {
    const body = trimmed.slice(1, -1);
    return trimmed[0] === '"'
      ? body.replace(/\\n/g, '\n').replace(/\\r/g, '\r').replace(/\\"/g, '"').replace(/\\\\/g, '\\')
      : body.replace(/\\'/g, "'");
  }
  return trimmed;
}

export function isValidEnvKey(key = '') {
  return ENV_KEY.test(String(key || '').trim());
}

export function parseDotEnv(rawString = '') {
  return joinContinuations(rawString)
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith('#'))
    .map((line) => {
      const match = line.match(/^(?:export\s+)?([A-Z_][A-Z0-9_]*)\s*=\s*([\s\S]*)$/);
      if (!match) return null;
      return {
        id: `envvar-${Date.now()}-${Math.random().toString(36).slice(2)}`,
        key: match[1],
        value: unquote(match[2]),
        masked: false,
        source: 'imported',
        enabled: true
      };
    })
    .filter(Boolean);
}

function prefixOf(key = '') {
  return key.includes('_') ? key.split('_')[0] : key;
}

function quoteValue(value = '') {
  const text = String(value);
  if (!text) return '""';
  if (/[\s#"'`$\\]/.test(text)) {
    return `"${text.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n')}"`;
  }
  return text;
}

export function serializeDotEnv(vars = []) {
  const exported = vars
    .filter((item) => item?.enabled !== false && !item?.masked && isValidEnvKey(item.key))
    .sort((a, b) => a.key.localeCompare(b.key));
  const lines = [`# Generated by NexCode - ${new Date().toISOString()}`];
  let lastPrefix = '';
  exported.forEach((item) => {
    const nextPrefix = prefixOf(item.key);
    if (lastPrefix && nextPrefix !== lastPrefix) {
      lines.push('');
    }
    lines.push(`${item.key}=${quoteValue(item.value)}`);
    lastPrefix = nextPrefix;
  });
  return `${lines.join('\n')}\n`;
}
