const DEFAULT_NODE_VERSION = '20.x';

function safeName(value = 'zenexcoder-app') {
  return String(value || 'zenexcoder-app')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 48) || 'zenexcoder-app';
}

export function parseEnvExample(content = '') {
  return String(content || '')
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith('#') && line.includes('='))
    .map((line) => {
      const index = line.indexOf('=');
      return {
        key: line.slice(0, index).trim(),
        value: line.slice(index + 1).trim(),
        masked: /KEY|TOKEN|SECRET|PASSWORD|PRIVATE/i.test(line.slice(0, index))
      };
    })
    .filter((item) => /^[A-Z_][A-Z0-9_]*$/.test(item.key));
}

export function detectProjectRuntime({ packageJson = {}, envExample = '', projectName = '' } = {}) {
  const scripts = packageJson.scripts || {};
  const dependencies = {
    ...(packageJson.dependencies || {}),
    ...(packageJson.devDependencies || {})
  };
  const envVars = parseEnvExample(envExample);

  const runtime = {
    projectName: safeName(packageJson.name || projectName),
    framework: 'node',
    nodeVersion: packageJson.engines?.node || DEFAULT_NODE_VERSION,
    buildCommand: scripts.build ? 'pnpm run build' : '',
    testCommand: scripts.test && !/echo .*no test/i.test(scripts.test) ? 'pnpm test' : '',
    startCommand: scripts.start ? 'pnpm start' : scripts.preview ? 'pnpm run preview' : '',
    outputDirectory: 'dist',
    envVars
  };

  if (dependencies.next) {
    runtime.framework = 'nextjs';
    runtime.outputDirectory = '.next';
  } else if (dependencies['@vitejs/plugin-react'] || dependencies.vite) {
    runtime.framework = 'vite';
    runtime.outputDirectory = 'dist';
  } else if (dependencies.react) {
    runtime.framework = 'react';
  } else if (dependencies.express || dependencies.fastify || dependencies.koa) {
    runtime.framework = 'node-api';
  }

  return runtime;
}

function terraformAws({ appName, healthPath }) {
  return `terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}

variable "aws_region" {
  type    = string
  default = "us-east-1"
}

variable "container_image" {
  type        = string
  description = "Container image for ${appName}. Set this before apply."
}

resource "aws_cloudwatch_log_group" "app" {
  name              = "/zenexcoder/${appName}"
  retention_in_days = 14
}

output "health_check_path" {
  value = "${healthPath}"
}
`;
}

function terraformGcp({ appName, healthPath }) {
  return `terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }
}

provider "google" {
  project = var.gcp_project
  region  = var.gcp_region
}

variable "gcp_project" {
  type = string
}

variable "gcp_region" {
  type    = string
  default = "us-central1"
}

resource "google_cloud_run_v2_service" "app" {
  name     = "${appName}"
  location = var.gcp_region

  template {
    containers {
      image = var.container_image
    }
  }
}

variable "container_image" {
  type        = string
  description = "Container image for ${appName}. Set this before apply."
}

output "health_check_path" {
  value = "${healthPath}"
}
`;
}

function serverlessAws({ appName, runtime }) {
  return `service: ${appName}
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: \${env:AWS_REGION, 'us-east-1'}
  environment:
${runtime.envVars.length ? runtime.envVars.map((item) => `    ${item.key}: \${env:${item.key}}`).join('\n') : '    NODE_ENV: production'}

functions:
  app:
    handler: server.handler
    events:
      - httpApi: '*'
`;
}

function vercelConfig({ appName, runtime }) {
  const buildCommand = runtime.buildCommand || undefined;
  const outputDirectory = runtime.outputDirectory || undefined;
  return JSON.stringify({
    name: appName,
    framework: runtime.framework === 'vite' ? 'vite' : undefined,
    buildCommand,
    outputDirectory,
    env: Object.fromEntries(runtime.envVars.map((item) => [item.key, `@${item.key.toLowerCase()}`]))
  }, null, 2);
}

function readme({ provider, runtime, appName }) {
  return `# ZenexCoder Deployment Plan

Provider: ${provider}
Project: ${appName}
Framework: ${runtime.framework}

This folder was generated by ZenexCoder CI/CD Autopilot. It is safe by default:
- dry-run is the default deployment mode
- production deploys require explicit approval from the UI
- secrets are read from active environment variables or provider CLIs, never hardcoded
- rollback metadata is tracked by the Electron CI/CD handler

Recommended commands:
${provider === 'vercel' ? '- vercel deploy --yes --token $VERCEL_TOKEN' : '- terraform init\n- terraform plan\n- terraform apply'}
`;
}

export function generateIaC({ provider = 'vercel', packageJson = {}, envExample = '', projectName = '', healthPath = '/health' } = {}) {
  const runtime = detectProjectRuntime({ packageJson, envExample, projectName });
  const appName = safeName(runtime.projectName || projectName);
  const normalizedProvider = ['aws', 'gcp', 'vercel'].includes(provider) ? provider : 'vercel';
  const files = [];

  if (normalizedProvider === 'aws') {
    files.push({ fileName: 'main.tf', content: terraformAws({ appName, healthPath }) });
    files.push({ fileName: 'serverless.yml', content: serverlessAws({ appName, runtime }) });
  } else if (normalizedProvider === 'gcp') {
    files.push({ fileName: 'main.tf', content: terraformGcp({ appName, healthPath }) });
  } else {
    files.push({ fileName: 'vercel.json', content: vercelConfig({ appName, runtime }) });
  }

  files.push({
    fileName: '.env.deploy.example',
    content: runtime.envVars.map((item) => `${item.key}=${item.masked ? '<set-in-active-env>' : item.value}`).join('\n')
  });
  files.push({ fileName: 'README.md', content: readme({ provider: normalizedProvider, runtime, appName }) });

  return { provider: normalizedProvider, runtime, appName, files };
}
